# Generated by Django 5.0.4 on 2024-05-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_sign',
            field=models.BooleanField(default=True, verbose_name='Опубликована'),
        ),
    ]
