# Generated by Django 5.0.4 on 2024-05-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
