# Generated by Django 5.0.4 on 2024-05-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productcreateview_alter_product_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCreateView',
        ),
    ]
