# Generated by Django 4.2.2 on 2024-05-25 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Введите категорию продукта', max_length=100, verbose_name='Категория')),
                ('description', models.TextField(blank=True, help_text='Введите описание категории продукта', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(help_text='Введите телефон', max_length=100, verbose_name='Телефон')),
                ('message', models.CharField(blank=True, help_text='Введите сообщение', max_length=100, null=True, verbose_name='Сообщение')),
                ('email', models.EmailField(blank=True, help_text='Введите адрес электронной почты', max_length=254, null=True, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта', max_length=100, verbose_name='Название продукта')),
                ('description', models.TextField(help_text='Введите описание продукта', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Введите фото продукта. если оно есть', null=True, upload_to='products/', verbose_name='Изображение')),
                ('price', models.IntegerField(help_text='Введите цену продукта', verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания релиза')),
                ('number_of_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('category', models.ForeignKey(help_text='Выберите категорию продукта', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Введите номер версии продукта', verbose_name='Номер версии')),
                ('version_name', models.CharField(help_text='Введите название версии продукта', max_length=150, verbose_name='Название версии')),
                ('version_now', models.BooleanField(default=True, verbose_name='Признак текущей версии')),
                ('product', models.ForeignKey(help_text='Выберите продукт', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
    ]
