# Generated by Django 4.2.2 on 2024-05-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('unpublish_product', 'Unpublish а product'), ('change_product_description', 'Change the description of any product'), ('change_product_category', 'Change the category of any product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
