# Generated by Django 4.2.2 on 2024-05-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_product_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('unpublish_product', 'Unpublish a product'), ('change_product_description', 'Change the description of any product'), ('change_product_category', 'Change the category of any product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
