# Generated by Django 5.0.4 on 2024-05-17 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_number_of_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCreateView',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
            ],
            bases=('catalog.product',),
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Введите категорию продукта', max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание категории продукта', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, help_text='Введите адрес электронной почты', max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='first_name',
            field=models.CharField(help_text='Введите имя', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='message',
            field=models.CharField(blank=True, help_text='Введите сообщение', max_length=100, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(help_text='Введите телефон', max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию продукта', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(help_text='Выберите дату создания продукта', verbose_name='Дата создания продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Введите описание продукта', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Введите фото продукта. если оно есть', null=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(help_text='Введите цену продукта', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(blank=True, help_text='Выберите дату релиза продукта', null=True, verbose_name='Дата релиза продукта'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Введите номер версии продукта', verbose_name='Номер версии')),
                ('version_name', models.CharField(help_text='Введите название версии продукта', max_length=150, verbose_name='Название версии')),
                ('version_now', models.BooleanField(default=True, verbose_name='Признак текущей версии')),
                ('product', models.ForeignKey(help_text='Выберите продукт', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
    ]
